import argparse

parser = argparse.ArgumentParser(description='VPTeA-VAD')
parser.add_argument('--seed', default=234, type=int)
parser.add_argument('--embed-dim', default=512, type=int)
parser.add_argument('--visual-length', default=256, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--visual-head', default=1, type=int)
parser.add_argument('--visual-layers', default=2, type=int)
parser.add_argument('--attn-window', default=8, type=int)
parser.add_argument('--classes-num', default=14, type=int)
parser.add_argument('--knowledge-base-path', default='src/ucf_knowledge_base.txt')

parser.add_argument('--max-epoch', default=5, type=int)
parser.add_argument('--model-path', default='model/model_ucf.pth')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint-path', default='model/checkpoint.pth')
parser.add_argument('--batch-size', default=32, type=int)
parser.add_argument('--train-list', default='list/ucf_CLIP_rgb.csv')
parser.add_argument('--test-list', default='list/ucf_CLIP_rgbtest.csv')
parser.add_argument('--gt-path', default='list/gt_ucf.npy')
parser.add_argument('--gt-segment-path', default='list/gt_segment_ucf.npy')
parser.add_argument('--gt-label-path', default='list/gt_label_ucf.npy')

parser.add_argument('--lr', default=5e-6)
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[4, 8])
parser.add_argument('--pair-loss-weight', default=0.10, type=float)
parser.add_argument('--ranking-loss-weight', default=0.05, type=float)
parser.add_argument('--ranking-margin', default=0.2, type=float)
parser.add_argument('--anomaly-sampling-power', default=0.5, type=float)
parser.add_argument('--map-gate-gamma', default=0.5, type=float)
