import argparse

parser = argparse.ArgumentParser(description='VPTeA-VAD')
parser.add_argument('--seed', default=234, type=int)
parser.add_argument('--embed-dim', default=512, type=int)
parser.add_argument('--visual-length', default=256, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--visual-head', default=1, type=int)
parser.add_argument('--visual-layers', default=1, type=int)
parser.add_argument('--attn-window', default=64, type=int)
parser.add_argument('--classes-num', default=7, type=int)
parser.add_argument('--knowledge-base-path', default='src/xd_knowledge_base.txt')

parser.add_argument('--max-epoch', default=15, type=int)
parser.add_argument('--model-path', default='model/model_xd.pth')
parser.add_argument('--use-checkpoint', action='store_true')
parser.add_argument('--checkpoint-path', default='model/checkpoint_xd.pth')
parser.add_argument('--batch-size', default=96, type=int)
parser.add_argument('--train-list', default='list/xd_CLIP_rgb.csv')
parser.add_argument('--test-list', default='list/xd_CLIP_rgbtest.csv')
parser.add_argument('--gt-path', default='list/gt.npy')
parser.add_argument('--gt-segment-path', default='list/gt_segment.npy')
parser.add_argument('--gt-label-path', default='list/gt_label.npy')

parser.add_argument('--lr', default=5e-6, type=float)
parser.add_argument('--scheduler-rate', default=0.1, type=float)
parser.add_argument('--scheduler-milestones', default=[6, 10, 14], nargs='+', type=int)
parser.add_argument('--pair-loss-weight', default=0.075, type=float)
parser.add_argument('--ranking-loss-weight', default=0.02, type=float)
parser.add_argument('--ranking-margin', default=0.2, type=float)
parser.add_argument('--map-gate-gamma', default=0.5, type=float)
